[general]
import = ["/home/doh/.config/alacritty/themes/rose-pine.toml"]

[font]
size = 14.0

[font.normal]
family = "JetBrainsMono NFM"
style = "Regular"

[window]
opacity = 1.0

[window.padding]
x = 30
y = 25
