import = ["/home/doh/.config/alacritty/colors.toml"]

[font]
size = 14.0

[font.bold]
family = "Hack Nerd Font"
style = "Bold"

[font.italic]
family = "Hack Nerd Font"
style = "Italic"

[font.normal]
family = "Hack Nerd Font"
style = "Regular"

[[keyboard.bindings]]
action = "SpawnNewInstance"
key = "Return"
mods = "Super|Shift"

[window]
opacity = 1.0

[window.padding]
x = 10
y = 10
