import = ["/home/doh/.config/alacritty/rose-pine.toml"]

[font]
size = 14.0

[font.bold]
family = "Writer"
style = "Bold"

[font.italic]
family = "Writer"
style = "Italic"

[font.normal]
family = "Writer"
style = "Regular"

[window]
opacity = 1

[window.padding]
x = 30
y = 25
