import = [".config/alacritty/colors.toml"]

[font]
size = 15.0

[font.bold]
family = "Writer"
style = "Bold"

[font.italic]
family = "Writer"
style = "Italic"

[font.normal]
family = "Writer"
style = "Regular"

[window]
opacity = 0.8

[window.padding]
x = 25
y = 25
